apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
  namespace: homepage
data:
  settings.yaml: |
    title: My Kubelab.sh
    theme: dark
  services.yaml: |
    - Cluster Services:
        - ArgoCD:
            href: https://argocd.kubelab.sh
            description: GitOps for Kubernetes
            icon: argo-cd.png
  bookmarks.yaml: |
    []
  widgets.yaml: |
    []
  kubernetes.yaml: |
    {}
  docker.yaml: |
    {}
