replicaCount: 1

persistence:
  enabled: true
  size: 10Gi
  storageClass: longhorn

postgresql-ha:
  enabled: false
postgresql:
  enabled: false

gitea:
  admin:
    existingSecret: forgejo-admin-secret
  config:
    database:
      DB_TYPE: sqlite3

ingress:
  enabled: true
  className: traefik
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: code.kubelab.sh
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
      - code.kubelab.sh
      secretName: forgejo-tls

