---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: forgejo-admin-secret
  namespace: forgejo
spec:
  encryptedData:
    password: AgCh+wcBHRBHuG5EXB0LqVG5GPgn03MHyltv436DWBd3UDXRyarJR6k1bZ7ouH00+oXj5xsQ6FoIgQDlYl4iMXn81Vp3gPx/NAPVZBPLq1UNSRIX9duwk1zkRSrfpU54EhJXAfdxs4Z520/XjUMbH34M1C6YVma7L+yBVb8XwFMuJwDaaSxI+r+zrmTEaF0+KGny8NtnUKzsZoWv7xxY7yh4N0tobzWjy87MaDTC3dg5B3eTwk4vYJ0yKFK6Blvg/F8DVsC36QpfXuAB+OuF4LWc/7NRoyn5yIAtbw7pmrRh8l8GyWWJP16ZdcFNLFKC1A85irsixtFmf+YGBgodRZXzOybGG+3sq4tQB+pOw047MKY8R0VAQUMLub8LwVeUdofHayInR0K7pPvn1IUa2nkixSvyy+kghJ67SytnnQ214w3J8S8qtGeHIC232cNchVtj6riavKzz870xm9qvLo20szBc3Z/nbPHNDM43lLpiTNBqMfo7SAXZwxR2Vete1JjHF7Ppz5WSg94ftSq/rP1TqzlUB8JJmw1Gve+KGWVw8uObrHGxPt++sjkAQVQcw6mufkmaP5uItZm7CTS7e0neiYX2auML59RH976Gop0hZOVTuNMGpoy+EqdZwvVNoeeKsgNqEEzWtrBft41RJK050/eSIkvv+lCj/S0gYfWQ37Gnp30AHZu354zzgXHLlfbtCwsSr99Zf10B4qkjJ7yBlbBwt2T2imiechZ45NByTw==
    username: AgBI5NH/NnP56pZPiEExcClr68tqOt/R7YNZd3duWori9P/nGtSyaNYOklVGOG8seY+okDvO1qRt0elPRT+Wf9kfswP71Cr4DpLBj6r6zksgQ+jqw8La9FphBdYT/FFIBjtBomZdqqAvV5aOluYl8cL67+Y8UkaLJVXcTa8xvIfpP8czEJdZGcwSvRzxUPnFMDyRzw7afPfWSHJHIgBF+H4aho5dpb3NouYlpBbcKmnBh0wIrmo4w7ou+QmFghB050mPfXvLVdkXSq2u3CPCEHdjPRwSo5BqeB4jt5jg4mOSf8amzAKu+e2lmPWQs+Fq6mDVu9f758zt/x+7H3Ew80sPRCjQQNgVvSZpoLl24zexg+IpKMHJwgilys6FZQXnfkCKumHL96KKJfhHJWpk4bDgDUbrf3BpFVIf9QJfq2c4JaTxsaMTr/khFmRmBBQqSk2b2/xv1pneedmW+f+XpnZYTNdIt8yVOWxVpXjsVNWrD76f3STFy3BzgkX6cWCOxVi+BkUTpTqEloCPJz2bEWkBJ9LZIFpkFZil4S4LMLF1vKFrt1iDk1KTCNMiD+KwX5sxdGfr4GSqKSjW9A8MQ8DNvr6YfJS4hWEX/v/ZjWfMNxNYR3WWsFkbb+FLfyIC5p4COQSpB01VnOUU+VpBXh9C5NImiW58B2dvsWAxpZNMPpkCsuQoh2vubA1fhbpU9iaSPE1/OQ==
  template:
    metadata:
      name: forgejo-admin-secret
      namespace: forgejo
